update validation script for safety

diff --git a/bin/validate_exercises b/bin/validate_exercises
--- a/bin/validate_exercises
+++ b/bin/validate_exercises
@@ -6,29 +6,28 @@
 set -o errexit
 set -o nounset
 
-root_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../ && pwd )"
-temp_folder_name="exercises_temp/"
-temp_folder="$root_path/$temp_folder_name"
+temp_folder=$(mktemp -d) || { echo "cannot make temp dir"; exit 1; }
 
 # Clean up after script on normal or forced exit
-trap "{ rm -rf $temp_folder; }" EXIT
+cleanup() { rm -r "$temp_folder"; }
+trap cleanup EXIT
 
-cp exercises $temp_folder -r
-cd $temp_folder
+cd "$( dirname "${BASH_SOURCE[0]}" )/.."
+cp -r ./exercises/* "$temp_folder"
 
+cd "$temp_folder"
 for exercise in *; do
-  cd $exercise
+  cd "$exercise"
   echo "Processing $exercise"
 
   # Replace "-" with "_" to follow bash conventions
-  exercise_name=$(echo "$exercise" | sed -r 's/[-]+/_/g')
-  test_file=${exercise_name}_test.sh
+  exercise_name=${exercise//-/_}
 
   # Create implementation file from example
-  cp example.sh ${exercise_name}.sh
+  ln -f example.sh "${exercise_name}.sh"
 
   # Run the tests
-  BATS_RUN_SKIPPED=true bats $test_file
+  BATS_RUN_SKIPPED=true bats "${exercise_name}_test.sh"
 
   cd ../
 done
