[v3] Move Practice Exercise example files to .meta directory (#484)
* [v3] Add Practice Exercise example files to .meta directory

The example implementation files for Practice Exercises should be located in the `.meta` directory. Besides being consistent with Concept Exercises, it also has the added benefit that no extra configuration is needed to prevent the example file from being downloaded to the student (as files in the `.meta` directory are never downloaded).

See [the spec](https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#file-example-implementation).

* Fix CI: the validation script looks in the .meta directory for the example solution

Co-authored-by: Glenn Jackman <jackman@pythian.com>

diff --git a/bin/validate_one_exercise b/bin/validate_one_exercise
--- a/bin/validate_one_exercise
+++ b/bin/validate_one_exercise
@@ -8,18 +8,20 @@ set -o nounset
 
 export BATS_RUN_SKIPPED=true    # run all the tests
 
-cd "$1" || {
-    echo "Cannot cd to $1" >&2
-    exit 1
-}
+die() { echo "$*" >&2; exit 1; }
 
-exercise=${1%/}            # strip a trailing slash, if there is one
-exercise=${exercise##*/}   # remove any leading path
+cd "$1" || die "Cannot cd to $1"
+
+exercise=${1%/}                 # strip a trailing slash, if there is one
+exercise=${exercise##*/}        # remove any leading path
+exercise_name=${exercise//-/_}  # replace "-" with "_" to follow convention
+solution="./.meta/example.sh"
+
+[[ -f ${exercise_name}.sh      ]] || die "Missing stub file for $exercise"
+[[ -f ${exercise_name}_test.sh ]] || die "Missing tests file for $exercise"
+[[ -f ${solution}              ]] || die "Missing solution file for $exercise"
 
 echo "Processing $exercise"
-
-# Replace "-" with "_" to follow bash conventions
-exercise_name=${exercise//-/_}
 
 cleanup() {
     git checkout "${exercise_name}.sh"
@@ -27,7 +29,7 @@ cleanup() {
 trap cleanup EXIT
 
 # Create implementation file from example
-cp example.sh "${exercise_name}.sh"
+cp "${solution}" "${exercise_name}.sh"
 
 # Run the tests
 bats "${exercise_name}_test.sh"
